<%@ Control Language="C#" AutoEventWireup="true" CodeFile="edit.ascx.cs" Inherits="widgets_Newsletter_edit" %>
<asp:GridView 
  runat="server"
  id="gridEmails"
  AlternatingRowStyle-BackColor="#F1F1F1"
  AutoGenerateColumns="False"
  AutoGenerateDeleteButton="true">
 
  <Columns>
    <asp:BoundField HeaderText="Email" DataField="innertext" />
  </Columns> 
</asp:GridView>