<%@ Page Language="C#" MasterPageFile="~/admin/admin1.master" AutoEventWireup="true" CodeFile="PingServices.aspx.cs" Inherits="admin_Pages_PingServices" Title="Ping services" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphAdmin" Runat="Server">

  <div class="settings">
  <h1>Ping Services</h1>

  <asp:TextBox runat="Server" ID="txtNewCategory" Width="300" MaxLength="255" />  
  <asp:Button runat="server" ID="btnAdd" ValidationGroup="new" />
  <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="Server" ValidationGroup="new" ControlToValidate="txtNewCategory" ErrorMessage="Please specify a ping service" /><br /><hr />

  <asp:GridView runat="server" ID="grid" 
    BorderColor="#f8f8f8" 
    BorderStyle="solid" 
    BorderWidth="1px" 
    RowStyle-BorderWidth="0"
    RowStyle-BorderStyle="None"
    gridlines="None"
    width="100%"
    AlternatingRowStyle-BackColor="#f8f8f8"
    AlternatingRowStyle-BorderColor="#f8f8f8" 
    HeaderStyle-BackColor="#F1F1F1"
    cellpadding="3"
    UseAccessibleHeader="true" 
    AutoGenerateColumns="false" 
    AutoGenerateDeleteButton="true" 
    AutoGenerateEditButton="true">
    <Columns>      
      <asp:TemplateField HeaderStyle-HorizontalAlign="Left" HeaderText="<%$ Resources:labels, name %>">
        <ItemTemplate>
          <%# Eval("value") %>
        </ItemTemplate>
        <EditItemTemplate>
          <asp:TextBox runat="server" ID="txtName" Width="100%" MaxLength="255" Text='<%# Eval("value") %>' />
        </EditItemTemplate>
      </asp:TemplateField>
    </Columns>
  </asp:GridView>
  </div>
</asp:Content>